rules:
  - id: avoid-system-out
    languages:
      - java
    patterns:
      - pattern: |
          $any.println($expr)
    message: "Avoid using print statements for logging"
    severity: WARNING

  - id: use-logger
    languages:
      - java
    patterns:
      - pattern: |
          $logger.getLogger($expr).log($args)
    message: "Prefer using a Logger for logging instead of direct log calls"
    severity: WARNING

  - id: avoid-java-util-date
    languages:
      - java
    patterns:
      - pattern: |
          new Date()
    message: "Avoid using java.util.Date; use java.time.Instant or java.time.LocalDateTime instead"
    severity: WARNING

  - id: avoid-string-equality
    languages:
      - java
      - javascript
      - python
      - go
      - ruby
      - c
      - cpp
      - csharp
      - objc
      - kotlin
      - swift
    patterns:
      - pattern: |
          $expr1 == $expr2
    message: "Avoid using == for String comparison; use equals() method instead"
    severity: WARNING

  - id: use-try-with-resources
    languages:
      - java
    patterns:
      - pattern: |
          try { $body } finally { $cleanup }
    message: "Consider using try-with-resources for better resource management"
    severity: WARNING

  - id: avoid-vector
    languages:
      - java
    patterns:
      - pattern: |
          new Vector()
    message: "Avoid using java.util.Vector; use java.util.ArrayList or java.util.LinkedList instead"
    severity: WARNING

  - id: use-stringbuilder-in-loop
    languages:
      - java
    patterns:
      - pattern: |
          $var = $var + $loopVar
    message: "Consider using StringBuilder for efficient string concatenation in a loop"
    severity: WARNING

  - id: avoid-unused-variable
    languages:
      - java
      - javascript
      - python
      - go
      - ruby
      - c
      - cpp
      - csharp
      - objc
      - kotlin
      - swift
    patterns:
      - pattern: |
          $type $var = $expr;
    message: "Avoid declaring unused variables"
    severity: WARNING
